server:
  port: 8080

# GitHub
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-secret:
            client-id:
# Google
          google:
            client-secret:
            client-id: